# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create-db.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_CreateMainWindow(object):
    def setupUi(self, CreateMainWindow):
        CreateMainWindow.setObjectName("CreateMainWindow")
        CreateMainWindow.resize(1629, 880)
        self.centralwidget = QtWidgets.QWidget(CreateMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1621, 811))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, -80, 1591, 821))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(280, 160, 301, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 155, 141, 41))
        self.label_2.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(660, 160, 91, 41))
        self.label_3.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(120, 270, 141, 41))
        self.label_4.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(520, 60, 491, 41))
        self.label_6.setStyleSheet("font: 75 18pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_6.setObjectName("label_6")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(770, 170, 95, 20))
        self.radioButton.setStyleSheet("font: 75 12pt \"Georgia\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(770, 210, 95, 20))
        self.radioButton_2.setStyleSheet("font: 75 12pt \"Georgia\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 270, 301, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(660, 270, 101, 41))
        self.label_5.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(760, 270, 301, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(120, 390, 141, 41))
        self.label_7.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 390, 301, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(660, 390, 141, 41))
        self.label_8.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(760, 400, 301, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(120, 550, 141, 41))
        self.label_9.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(280, 550, 301, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(520, 680, 291, 41))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 77);\n"
"font: 75 14pt \"Georgia\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        CreateMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1629, 26))
        self.menubar.setObjectName("menubar")
        CreateMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateMainWindow)
        self.statusbar.setObjectName("statusbar")
        CreateMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CreateMainWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateMainWindow)

    def retranslateUi(self, CreateMainWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateMainWindow.setWindowTitle(_translate("CreateMainWindow", "CreateMainWindow"))
        self.label_2.setText(_translate("CreateMainWindow", "Criminal Name"))
        self.label_3.setText(_translate("CreateMainWindow", "Gender"))
        self.label_4.setText(_translate("CreateMainWindow", "Age"))
        self.label_6.setText(_translate("CreateMainWindow", "CREATE CRIMINAL DATABASE"))
        self.radioButton.setText(_translate("CreateMainWindow", "Male"))
        self.radioButton_2.setText(_translate("CreateMainWindow", "Female"))
        self.label_5.setText(_translate("CreateMainWindow", "Crime"))
        self.label_7.setText(_translate("CreateMainWindow", "Last Found"))
        self.label_8.setText(_translate("CreateMainWindow", "State"))
        self.label_9.setText(_translate("CreateMainWindow", "Upload Images"))
        self.pushButton.setText(_translate("CreateMainWindow", "CREATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateMainWindow = QtWidgets.QMainWindow()
    ui = Ui_CreateMainWindow()
    ui.setupUi(CreateMainWindow)
    CreateMainWindow.show()
    sys.exit(app.exec_())
