# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame
import cv2
from createdb import Ui_CreateMainWindow
import login
from subprocess import call, Popen


class Ui_HomeMainWindow(object):
    frame: QFrame

    def openWindowCreate(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CreateMainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openWindowlogin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = login.Ui_loginMainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def Start(self):
        call(['python', "main.py"])

    def detectImage(self):
        Popen(['python', 'Image-detect.py'])

    def Realtime(self):
        Popen(['python', 'test.py'])

    def setupUi(self, HomeMainWindow):
        HomeMainWindow.setObjectName("HomeMainWindow")
        HomeMainWindow.resize(1632, 1035)
        self.centralwidget = QtWidgets.QWidget(HomeMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, 0, 1561, 1131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(390, 0, 1001, 1051))
        self.label.setStyleSheet("image: url(:/newPrefix/home.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.create_btn = QtWidgets.QPushButton(self.frame, clicked=lambda: self.openWindowCreate())
        self.create_btn.setGeometry(QtCore.QRect(870, 250, 181, 41))
        self.create_btn.setStyleSheet("font: 75 12pt \"Georgia\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(0, 0, 59);")
        self.create_btn.setObjectName("create_btn")
        self.detect_btn = QtWidgets.QPushButton(self.frame)
        self.detect_btn.setGeometry(QtCore.QRect(870, 470, 181, 41))
        self.detect_btn.setStyleSheet("font: 75 12pt \"Georgia\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(0, 0, 59);")
        self.detect_btn.setObjectName("detect_btn")
        self.detect_btn.clicked.connect(self.detectImage)
        self.start_btn = QtWidgets.QPushButton(self.frame)
        self.start_btn.clicked.connect(self.Start)
        self.start_btn.setGeometry(QtCore.QRect(870, 700, 181, 41))
        self.start_btn.setStyleSheet("font: 75 12pt \"Georgia\";\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(0, 0, 59);")
        self.start_btn.setObjectName("start_btn")
        self.start_btn.clicked.connect(self.Realtime)
        self.view_btn = QtWidgets.QPushButton(self.frame)
        self.view_btn.setGeometry(QtCore.QRect(870, 930, 181, 41))
        self.view_btn.setStyleSheet("font: 75 12pt \"Georgia\";\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "background-color: rgb(0, 0, 59);")
        self.view_btn.setObjectName("view_btn")
        self.signout_button = QtWidgets.QPushButton(self.frame, clicked=lambda: self.openWindowlogin())
        self.signout_button.setGeometry(QtCore.QRect(1220, 10, 111, 41))
        self.signout_button.setStyleSheet("font: 75 10pt \"Georgia\";\n"
                                          "color: rgb(0, 0, 77);")
        self.signout_button.setObjectName("signout_button")
        self.about_button = QtWidgets.QPushButton(self.frame)
        self.about_button.setGeometry(QtCore.QRect(960, 10, 111, 41))
        self.about_button.setStyleSheet("font: 75 10pt \"Georgia\";\n"
                                        "color: rgb(0, 0, 77);")
        self.about_button.setObjectName("about_button")
        self.contact_button = QtWidgets.QPushButton(self.frame)
        self.contact_button.setGeometry(QtCore.QRect(1090, 10, 111, 41))
        self.contact_button.setStyleSheet("font: 75 10pt \"Georgia\";\n"
                                          "color: rgb(0, 0, 77);")
        self.contact_button.setObjectName("contact_button")
        self.CriminalEye_label = QtWidgets.QLabel(self.frame)
        self.CriminalEye_label.setGeometry(QtCore.QRect(550, 30, 191, 41))
        self.CriminalEye_label.setStyleSheet("font: 75 18pt \"Georgia\";\n"
                                   "color: rgb(255, 255, 255);")
        self.CriminalEye_label.setObjectName("CriminalEye_label")
        HomeMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeMainWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeMainWindow)

    def retranslateUi(self, HomeMainWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeMainWindow.setWindowTitle(_translate("HomeMainWindow", "HomeMainWindow"))
        self.create_btn.setToolTip(_translate("HomeMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.create_btn.setWhatsThis(_translate("HomeMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.create_btn.setText(_translate("HomeMainWindow", "CREATE"))
        self.detect_btn.setToolTip(_translate("HomeMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.detect_btn.setWhatsThis(_translate("HomeMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.detect_btn.setText(_translate("HomeMainWindow", "DETECT"))
        self.start_btn.setToolTip(_translate("HomeMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.start_btn.setWhatsThis(_translate("HomeMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.start_btn.setText(_translate("HomeMainWindow", "START"))
        self.view_btn.setToolTip(_translate("HomeMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.view_btn.setWhatsThis(_translate("HomeMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.view_btn.setText(_translate("HomeMainWindow", "VIEW"))
        self.signout_button.setText(_translate("HomeMainWindow", "SIGN OUT"))
        self.about_button.setText(_translate("HomeMainWindow", "ABOUT"))
        self.contact_button.setText(_translate("HomeMainWindow", "CONTACT"))
        self.CriminalEye_label.setText(_translate("HomeMainWindow", "Criminal Eye"))


import home_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    HomeMainWindow = QtWidgets.QMainWindow()
    ui = Ui_HomeMainWindow()
    ui.setupUi(HomeMainWindow)
    HomeMainWindow.show()
    sys.exit(app.exec_())
