# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import home
from register import Ui_RegisterMainWindow
import mysql.connector as con

class Ui_loginMainWindow(object):
    def openWindowHome(self):
        db=con.connect(host="localhost", user="root", password="", database="studentdb")
        c=db.cursor()
        un=self.Username_edit.text()
        pw=self.password_edit.text()

        c.execute("SELECT * FROM exp1 WHERE Username='"+un+"' AND Password = '"+pw+"'")
        result = c.fetchone()
        if result:
            self.window=QtWidgets.QMainWindow()
            self.ui=home.Ui_HomeMainWindow()
            self.ui.setupUi(self.window)
            self.window.show()
        

    def openWindowRegister(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_RegisterMainWindow()
        self.ui.setupUi(self.window)
        self.window.show()





    def setupUi(self, loginMainWindow):
        loginMainWindow.setObjectName("loginMainWindow")
        loginMainWindow.resize(1643, 997)
        self.centralwidget = QtWidgets.QWidget(loginMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(340, 100, 1041, 851))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-30, 0, 1101, 851))
        self.label.setStyleSheet("image: url(:/login/Login.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Username_edit = QtWidgets.QLineEdit(self.frame)
        self.Username_edit.setGeometry(QtCore.QRect(210, 310, 251, 51))
        self.Username_edit.setStyleSheet("color: rgb(0, 0, 77);\n"
"\n"
"font: 75 12pt \"Georgia\";")
        self.Username_edit.setText("")
        self.Username_edit.setObjectName("Username_edit")
        self.password_edit = QtWidgets.QLineEdit(self.frame)
        self.password_edit.setGeometry(QtCore.QRect(210, 450, 251, 51))
        self.password_edit.setStyleSheet("color: rgb(0, 0, 77);\n"
"font: 75 12pt \"Georgia\";")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(210, 280, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(210, 425, 121, 21))
        self.label_3.setObjectName("label_3")
        self.login_button = QtWidgets.QPushButton(self.frame, clicked=lambda: self.openWindowHome())
        self.login_button.setGeometry(QtCore.QRect(140, 610, 131, 51))
        self.login_button.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.login_button.setObjectName("login_button")
        self.signup_button = QtWidgets.QPushButton(self.frame, clicked=lambda: self.openWindowRegister())
        self.signup_button.setGeometry(QtCore.QRect(300, 610, 141, 51))
        self.signup_button.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.signup_button.setObjectName("signup_button")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(300, 580, 171, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(560, 340, 441, 101))
        self.label_5.setStyleSheet("font: 75 18pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.label_5.setObjectName("label_5")
        loginMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(loginMainWindow)
        QtCore.QMetaObject.connectSlotsByName(loginMainWindow)

    def retranslateUi(self, loginMainWindow):
        _translate = QtCore.QCoreApplication.translate
        loginMainWindow.setWindowTitle(_translate("loginMainWindow", "loginMainWindow"))
        self.label_2.setText(_translate("loginMainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">User Name</span></p></body></html>"))
        self.label_3.setText(_translate("loginMainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.login_button.setText(_translate("loginMainWindow", "LOGIN"))
        self.signup_button.setText(_translate("loginMainWindow", "SIGN UP"))
        self.label_4.setText(_translate("loginMainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Don\'t have an account?</span></p></body></html>"))
        self.label_5.setText(_translate("loginMainWindow", "WELCOME TO CRIMINAL EYE"))
import login_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginMainWindow = QtWidgets.QMainWindow()
    ui = Ui_loginMainWindow()
    ui.setupUi(loginMainWindow)
    loginMainWindow.show()
    sys.exit(app.exec_())
