# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1643, 997)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(340, 100, 1041, 851))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-30, 0, 1101, 851))
        self.label.setStyleSheet("image: url(:/login/Login.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Username_edit = QtWidgets.QLineEdit(self.frame)
        self.Username_edit.setGeometry(QtCore.QRect(210, 310, 251, 51))
        self.Username_edit.setStyleSheet("color: rgb(0, 0, 77);\n"
"\n"
"font: 75 12pt \"Georgia\";")
        self.Username_edit.setText("")
        self.Username_edit.setObjectName("Username_edit")
        self.password_edit = QtWidgets.QLineEdit(self.frame)
        self.password_edit.setGeometry(QtCore.QRect(210, 450, 251, 51))
        self.password_edit.setStyleSheet("color: rgb(0, 0, 77);\n"
"font: 75 12pt \"Georgia\";")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(210, 280, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(210, 425, 121, 21))
        self.label_3.setObjectName("label_3")
        self.login_button = QtWidgets.QPushButton(self.frame)
        self.login_button.setGeometry(QtCore.QRect(140, 610, 131, 51))
        self.login_button.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.login_button.setObjectName("login_button")
        self.signup_button = QtWidgets.QPushButton(self.frame)
        self.signup_button.setGeometry(QtCore.QRect(300, 610, 141, 51))
        self.signup_button.setStyleSheet("font: 75 12pt \"Georgia\";\n"
"color: rgb(0, 0, 77);")
        self.signup_button.setObjectName("signup_button")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(300, 580, 171, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">User Name</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.login_button.setText(_translate("MainWindow", "LOGIN"))
        self.signup_button.setText(_translate("MainWindow", "SIGN UP"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Don\'t have an account?</span></p></body></html>"))
import login_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
